name: instant_messenger_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  cloud_firestore: ^5.6.5
  envied: ^1.1.1
  firebase_core: ^3.12.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  envied_generator: ^1.1.1
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  assets:
    - assets/images/
